### ISSUE TITLE
Starter with ESP32-DevKitC doesn't work with iOS

### ISSUE THREAD

**Issue by jcyh0120** [line/line-things-starter#6]
I tried the tutorial of this article [LINE の IoT プラットフォーム LINE Things の Developer Trial を試してみる](https://engineering.linecorp.com/ja/blog/line-things-developer-trial/).

It did work with android phone but ios phone cannot turn on the led. But the button status on device does sync back to LIFF app.

I've tried unpairing and forget the BLE device and restart iphone but no luck.

**Update:**
I found the pattern and know how to tell if it works or not. 
- When entering the LIFF App, if the popup shows up "pairing ESP32", quickly click pair. Then the LED button would work.

- If the popup didn't show up or I didn't click pair, the popup disappear automatically and the LED button would not work.

Here's the video to show both situations.
- Not Work: https://www.youtube.com/watch?v=d9OtJX2tIa8
- Work: https://www.youtube.com/watch?v=qyHtst_H7v4

**Comment by teknuze** [comment]
Since the properties of the characteristics are secured, a secured connection (with pairing) is required for the smartphone to access the secured characteristics. For some reason, I am unable to view the videos you have posted, YouTube tells me the both videos are unavailable. However, from my understanding of the issue I believe that this may help resolve your issue. 
Could you try changing line 66 from
`  thingsSecurity->setAuthenticationMode(ESP_LE_AUTH_BOND);`
to
`thingsSecurity->setAuthenticationMode(ESP_LE_AUTH_REQ_SC_ONLY);`
and see if that resolves your issue?

**Comment by jcyh0120** [comment]
@teknuze Thanks, it works!! Solved my problem. Struggling for almost a week.

Sorry that I didn't set the permission of youtube video correctly.
It should be available now.

**Comment by teknuze** [comment]
Fixed in commit 35932288ec4e631a859fd5ec8a39375ec59a5c92
